# batalla_ayacucho.py
# Datos generales reales sobre la Batalla de Ayacucho (Perú, 1824)

def datos_batalla_ayacucho():
    print("==============================================")
    print("           BATALLA DE AYACUCHO (1824)         ")
    print("==============================================")
    print("Fecha: 9 de diciembre de 1824")
    print("Lugar: Pampas de la Quinua, distrito de Quinua, región Ayacucho, Perú")
    print("Altitud aproximada: 3,400 m s.n.m.")
    print("")
    print("Comandantes principales:")
    print(" - Patriotas: Antonio José de Sucre")
    print(" - Realistas: José de La Serna (Virrey) y José de Canterac")
    print("")
    print("Resultado: Victoria del Ejército Unido Libertador")
    print("Consecuencia: Rendición del ejército realista mediante la Capitulación de Ayacucho")
    print("Importancia histórica:")
    print(" - Selló la independencia del Perú")
    print(" - Marcó el fin del dominio español en Sudamérica")
    print("")
    print("Santuario histórico:")
    print(" - La Pampa de Ayacucho fue declarada Santuario Histórico Nacional")
    print("")
    print("Monumento conmemorativo:")
    print(" - Obelisco de la Pampa de la Quinua (44 metros de altura)")
    print(" - Inaugurado en 1974 para conmemorar el 150 aniversario de la batalla")
    print("==============================================")

if __name__ == "__main__":
    datos_batalla_ayacucho()
